# Generated by Django 4.2.15 on 2024-08-07 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Coures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=20, null=True)),
                ('moblie', models.CharField(max_length=10, null=True)),
                ('placement', models.BooleanField(null=True)),
                ('fees', models.IntegerField(default=0)),
                ('gst', models.FloatField(default=0)),
                ('total_fees', models.IntegerField(default=0)),
                ('paid_fees', models.IntegerField(default=0)),
                ('remaining_fees', models.IntegerField(default=0)),
                ('pictuer', models.ImageField(null=True, upload_to='images/')),
                ('selected_coures', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Coures.coures')),
            ],
        ),
    ]
