# Generated by Django 4.2.15 on 2024-08-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, null=True)),
                ('Body', models.TextField(null=True)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
    ]
