# Generated by Django 4.2.15 on 2024-08-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coures', models.CharField(max_length=20, null=True)),
                ('duration', models.CharField(max_length=20, null=True)),
                ('fees', models.FloatField(default=0)),
                ('gst', models.FloatField(default=0)),
                ('final_fees', models.FloatField(default=0)),
            ],
        ),
    ]
